doc.type.html
script
html
head
utf8
viewportcontent=width=device-width,initial-scale=one
title covid strings16 first round bracket
div id bracket class bracket div
script src bracket.js
link rel= stylesheet href=css
head
body
bracket-container{}
matchup
solid zero;
padding 
text align center 
filename=covid strings16 first round.js
first round=(highest overall seed,second highest seed third highest seed first middle seed, second middle seed,  third lowest seed ,second lowest seed,lowest overall seed)
highest overall seed = 1 seed
second highest seed=2seed
third highest seed=3 seed
firstmiddleseed=4seed
second middle seed = 5 seed
third lowest seed= 6 seed
second lowest seed = 7 seed
lowest overall seed = 8 seed
covidstrings team list16=[indigo,burgundy,green,teal,turquoise,orange,purple,yellow]
matchup1=(orange versus green)
matchup2=(yellow versus indigo)
matchup3=(purple versus burgundy)
matchup4=(turquoise versus teal)
bracket =getelementbyid(bracket);
document.createelement 
matchupdiv.classname=(matchup)
matchupdiv.inner html =[matchup]
rounddiv.appendchild(matchup)
for (i in covid strings first round)
round div=create element
round div class name=covid strings16 first round
bracket.appendchild(round div)
if (event.target.covid strings seed list.contains(matchup))
event.target.covid strings seed list.toggle
else:
addmatchup
java util.scanner
java.util
questions[]questions={
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
if selectedanswer==correct:
return true
else:
return false
advancingteam=slice(current teams)
declarewinner
result=declarewinner(matchup1)
if green score>=forty:
console.log(green peacemakers win)
else:
console.log(orange rna messengers win)
result=declarewinner(matchup2)
if indigo score>=forty:
console.log(indigo isos win)
else:
console.log(yellow moxie wins)
result=declarewinner(matchup3)
if burgundy score>=forty:
console.log(burgundy rebuilders win)
else:
console.log(purple brave hearts win)
result=declarewinner(matchup4)
if teal score>=forty:
console.log(teal terminators win)
else:
console.log(turquoise waves win)
return filename
