doc.type.html
script
filename=covid strings 16 key words.js
covid strings16 key word list=[economy,mike pences denial covid first wave,reintroducing mask mandates,novavax vaccine,100-57,really weird symptoms,things worse earlier,top one percent of covid avoiders,2020 pandemic,Brain Control Bioweapons,Vaccine, second chance,dumbest controversy, nascar series, failure pandemic,capital one relief valve, not relatable,RFK’s covid claim,nikki manaj’s cousin’s friend]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
covid strings16 reference list=[a:student loan payments restarted after a covid pause.why the economy is barely feeling it.(msn.com),b:pence denies threat of second coronavirus wave,touts $400 billion infrastructure bill(yahoo.com),c:the first wave |national geographic documentary films,d:covid map shows states with highest cases as hospital mask mandates return (msn.com),e:a new covid shot is more effective against current variants and may have fewer side effects (msn.com),f:poll:americans not buying white house spin on coronavirus |ap news,g:latest covid variant has some unusual symptoms to look out for (msn.com),
h:the bubble review:judd apatow makes a bad movie about a worse one (variety.com),i:sanders tests positive for covid-19 during senate break as infections rise nationally (msn.com),j:bing videos,k:word of the year 2020 |pandemic |merriam-webster,m:gordon chang exposes chinas experimentation:clearly it is a biological weapon(msn.com),n:word of the year 2021 |vaccine |merriam-webster,o:jeopardy! second chance tournament sets contestants (vulture.com),p:nicki minajs cousins friends balls,explained |gq,
q:2020 enascar iracing pro invitational series - wikipedia,r:covid could trigger heart failure pandemic as experts warn of global healthcare risk(msn.com).s:cnn international to broadcast turner sports exclusive presentation of capital ones the match:champions for charity,t:the bubble & other covid comedies keep missing the point (screenrant.com),u:robert f.kennedy jr.caught on tape floating stunning claim about covid and jews (msn.com),v:nicki minajs covid-19 vaccine tweets are raising eyebrows -los angeles times (latimes.com)]
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
B= Pc.CreateScript(B);
B.Attributes.Add(Foobar,{Type:Entity});
B.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
C= Pc.CreateScript(C);
C.Attributes.Add(Foobar,{Type:Entity});
C.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
D=Pc.CreateScript(D);
D.Attributes.Add(Foobar,{Type:Entity});
D.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
E=Pc.CreateScript(E);
E.Attributes.Add(Foobar,{Type:Entity});
E.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
F=Pc.CreateScript(F);
F.Attributes.Add(Foobar,{Type:Entity});
F.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
G=Pc.CreateScript(G);
G.Attributes.Add(Foobar,{Type:Entity});
G.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
H=Pc.CreateScript(H);
H.Attributes.Add(Foobar,{Type:Entity});
H.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
I=Pc.CreateScript(I);
I.Attributes.Add(Foobar,{Type:Entity});
I.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
J=Pc.CreateScript(J);
J.Attributes.Add(Foobar,{Type:Entity});
J.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
K=Pc.CreateScript(K);
K.Attributes.Add(Foobar,{Type:Entity});
K.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
L=Pc.CreateScript(L);
L.Attributes.Add(Foobar,{Type:Entity});
L.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
M=Pc.CreateScript(M);
M.Attributes.Add(Foobar,{Type:Entity});
M.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
N=Pc.CreateScript(N);
N.Attributes.Add(Foobar,{Type:Entity});
N.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
O=Pc.CreateScript(O);
O.Attributes.Add(Foobar,{Type:Entity});
O.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
P=Pc.CreateScript(P);
P.Attributes.Add(Foobar,{Type:Entity});
P.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
Q=Pc.CreateScript(Q);
Q.Attributes.Add(Foobar,{Type:Entity});
Q.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
R=Pc.CreateScript(R);
R.Attributes.Add(Foobar,{Type:Entity});
R.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
S=Pc.CreateScript(S);
S.Attributes.Add(Foobar,{Type:Entity});
S.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
T=Pc.CreateScript(T);
T.Attributes.Add(Foobar,{Type:Entity});
T.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
U=Pc.CreateScript(U);
U.Attributes.Add(Foobar,{Type:Entity});
U.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (this.entity)
v=pc.create script(v);
v.attributes.add(foobar,{type:entity});
v.prototype.initialize=function() 
console.log(this.foobar.name);
return filename

