doc.type.html
html lang en 
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’welcome to covid strings16
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=keywords
heading2=online references 
heading3=script templates
filename=covid strings 16 key words.js
<header.html>
keywords
key search words for covid strings16
covid strings16 key word list=[economy,mike pences denial covid first wave,reintroducing mask mandates,novavax vaccine,100-57,really weird symptoms,things worse earlier,top one percent of covid avoiders,2020 pandemic,brain control bioweapons,vaccine, second chance,dumbest controversy, nascar series, failure pandemic,capital one relief valve, not relatable,rfk’s covid claim,nikki manaj’s cousin’s friend]
string manager non-concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
string manager concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings key word list
select characters
edit diffuse property
desired color=green
<header.html>
online references 
links to articles that correspond to phrases in covid strings16
covid strings16 reference list=[a:student loan payments restarted after a covid pause.why the economy is barely feeling it.(msn.com),b:pence denies threat of second coronavirus wave,touts $400 billion infrastructure bill(yahoo.com),c:the first wave |national geographic documentary films,d:covid map shows states with highest cases as hospital mask mandates return (msn.com),e:a new covid shot is more effective against current variants and may have fewer side effects (msn.com),f:poll:americans not buying white house spin on coronavirus |ap news,g:latest covid variant has some unusual symptoms to look out for (msn.com),
h:the bubble review:judd apatow makes a bad movie about a worse one (variety.com),i:sanders tests positive for covid-19 during senate break as infections rise nationally (msn.com),j:bing videos,k:word of the year 2020 |pandemic |merriam-webster,m:gordon chang exposes chinas experimentation:clearly it is a biological weapon(msn.com),n:word of the year 2021 |vaccine |merriam-webster,o:jeopardy! second chance tournament sets contestants (vulture.com),p:nicki minajs cousins friends balls,explained |gq,
q:2020 enascar iracing pro invitational series - wikipedia,r:covid could trigger heart failure pandemic as experts warn of global healthcare risk(msn.com).s:cnn international to broadcast turner sports exclusive presentation of capital ones the match:champions for charity,t:the bubble & other covid comedies keep missing the point (screenrant.com),u:robert f.kennedy jr.caught on tape floating stunning claim about covid and jews (msn.com),v:nicki minajs covid-19 vaccine tweets are raising eyebrows -los angeles times (latimes.com)]
<header.html>
script templates
code for accessing the references
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet(this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.create script(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.Find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h=pc.create script(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
i=pc.create script(i);
i.attributes.add(foobar,{type:entity});
i.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
j=pc.create script(j);
j.attributes.add(foobar,{type:entity});
j.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
k=pc.create script(k);
k.attributes.add(foobar,{type:entity});
k.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
l=pc.create script(l);
l.attributes.add(foobar,{type:entity});
l.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize =function() 
console.log(this.foobar.name);
asset= this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar,{type:entity});
p.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app .assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
q=pc.create script(q);
q.attributes.add(foobar,{type:entity});
q.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
r=pc.create script(r);
r.attributes.add(foobar,{type:entity});
r.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
s=pc.create script(s);
s.attributes.add(foobar,{type:entity});
s.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
t=pc.create script(t);
t.attributes.add(foobar,{type:entity});
t.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
u=pc.create script(u);
u.attributes.add(foobar,{type:entity});
u.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
v=pc.create script(v);
v.attributes.add(foobar,{type:entity});
v.prototype.initialize=function() 
console.log(this.foobar.name);
return filename
